version: '3.7'

services:
  java:
    image: openjdk:11
    volumes:
      - ./:/app
    command: bash -c "cd /app && java -jar partner-service-1.0-all.jar"
    ports:
      - 8080:8080

volumes:
  data: